import { useNavigate, useParams } from 'react-router-dom'
import { BackLink, EmptyState } from '@/components/patterns'
import { SettingsGroup, SettingsRow } from '@/components/settings'
import { LEGAL_DOCUMENTS } from '@/routes/settings/legal-content'

/**
 * Legal text, rendered in the app rather than opened in a browser.
 *
 * Deciding whether to trust an app with your machine should not require that
 * app to be online — and this one has nowhere to fetch the text from anyway.
 */
export default function LegalScreen() {
  const { document: documentId } = useParams<{ document: string }>()
  const doc = documentId ? LEGAL_DOCUMENTS[documentId] : undefined

  if (!doc) {
    return (
      <div className="flex h-full items-center justify-center p-8">
        <EmptyState title="Not found" description="That document does not exist." />
      </div>
    )
  }

  return (
    <div className="flex h-full flex-col overflow-y-auto">
      <div className="mx-auto flex w-full max-w-2xl flex-col gap-6 p-6">
        <BackLink to="/settings/legal" label="Legal info" />

        <div>
          <h1 className="text-title-2 font-bold text-content-primary">{doc.title}</h1>
          <p className="mt-1 text-caption text-content-muted">Last updated: {doc.updated}</p>
          <p className="mt-3 text-body leading-6 text-content-secondary">{doc.intro}</p>
        </div>

        <div className="flex flex-col gap-6">
          {doc.sections.map((section) => (
            <section key={section.heading} className="flex flex-col gap-1.5">
              <h2 className="text-headline font-semibold text-content-primary">{section.heading}</h2>
              <p className="selectable text-body leading-6 text-content-secondary">{section.body}</p>
            </section>
          ))}
        </div>
      </div>
    </div>
  )
}

/** Muse's Legal info: the AI notice, then every document the app ships. */
export function LegalInfoScreen() {
  const navigate = useNavigate()
  return (
    <div className="h-full w-full overflow-y-auto bg-bg-base">
      <div className="drag h-11 w-full shrink-0" />
      <div className="no-drag mx-auto flex w-full max-w-content flex-col gap-6 px-8 pb-16">
        <h1 className="text-title-1 font-bold text-content-primary">Legal info</h1>
        <p className="text-footnote text-content-primary">Responses are generated by AI. Some may be inaccurate or inappropriate.</p>
        <SettingsGroup>
          {Object.entries(LEGAL_DOCUMENTS).map(([id, doc]) => (
            <SettingsRow key={id} label={`ClawMuse ${doc.title === 'Privacy' ? 'Privacy Policy' : doc.title}`} onClick={() => navigate(`/settings/legal/${id}`)} />
          ))}
        </SettingsGroup>
      </div>
    </div>
  )
}
