// Runs after electron-builder assembles the .app but before it is signed
// (platformPackager: emitAfterPack → … → doSignAfterPack), which is the only
// window where bundle resources can still be replaced without invalidating the
// code signature.
//
// Why this exists: `mac.icon` points at build/icon.icon so macOS 26 gets a real
// Assets.car + CFBundleIconName. As a side effect electron-builder derives the
// legacy Contents/Resources/icon.icns from that same .icon via actool — and
// actool only emits FOUR slots (16, 16@2x, 128, 128@2x). On macOS 15 and
// earlier, which have no Assets.car path at all, that leaves Finder and Quick
// Look upscaling a 256px bitmap to 512 and 1024. build/icon.icns, generated by
// scripts/generate-icons.sh, carries the full ten-slot set, so put it back.
import { copyFile, readFile } from 'node:fs/promises'
import path from 'node:path'

const ICNS_MAGIC = 'icns'

export default async function afterPack(context) {
  if (context.electronPlatformName !== 'darwin') return

  const projectDir = context.packager.info.projectDir
  const appName = context.packager.appInfo.productFilename
  const target = path.join(context.appOutDir, `${appName}.app`, 'Contents', 'Resources', 'icon.icns')
  const source = path.join(projectDir, 'build', 'icon.icns')

  // A truncated or missing source would silently downgrade the icon on older
  // macOS, so fail the build rather than ship it.
  const buf = await readFile(source)
  if (buf.subarray(0, 4).toString('ascii') !== ICNS_MAGIC) {
    throw new Error(`${source} is not a valid .icns file`)
  }

  await copyFile(source, target)
  console.log(`  • afterPack        replaced icon.icns with the full-resolution set (${buf.length} bytes)`)
}
